### ISSUE TITLE
update docu about auto generated release log

### ISSUE THREAD

**Issue by andreakreichgauer** [dot-base/.github#54]
update in Notion:
https://www.notion.so/dotbase/Releases-CI-Pipeline-70087f97d96f43eb8ab48299e3cd4210?pvs=4

**Comment by Zbozi** [comment]
Good read. To clarify even further I would suggest to seperate the concers of the regular release and the the hotfix release into seperate paragraphs. 

## Release Process Overview

We categorize our releases into two types: regular releases and hotfix releases. Each type of release follows a specific process due to the nature of the changes they incorporate.

### Regular Releases:
- **Merge Process:** Regular releases primarily involve merging changes from the `main` branch into the `release` branch.
- **Automation:** To initiate a regular release, use the *Create Release PR* action on GitHub. This action can be triggered manually either through the GitHub Web UI or via the GitHub CLI.
- **Review and Merge:** The Pull Request (PR) created by the *dotbase-bot* must receive at least two approving reviews. The PR is then merged automatically without manual intervention and is not squashed.
- **Post-Merge Actions:** Following the merge, the `main` branch is fast-forwarded to match the `release` branch. A new GitHub Release and Docker image are then automatically created.

### Hotfix Releases:
- **Need for Hotfixes:** Hotfixes are necessary when urgent changes must be made to a service release, particularly when other changes have already been merged into the `main` branch since the last release.
- **Branch and Merge Process:** Hotfixes are created from a fix branch that includes individual fix commits formatted as `fix: serious bug`. The hotfix branch is then merged into the `release` branch.
- **Automation:** Initiate a hotfix release using the ***Create Hotfix PR*** action on GitHub.
- **Sync with Main:** After the hotfix merge, a sync PR is automatically created from `main` into a branch named `sync/HOTFIX_RELEASE_VERSION_TAG`. Resolving any conflicts between the hotfix and concurrent changes on `main` is necessary before the sync PR can be reviewed and merged.
- **Review and Merge:** The sync PR requires at least one approving review and, like other merges, it is performed automatically and should not be done manually.
- **Post-Merge Actions:** Once merged, `main` is fast-forwarded to the sync branch, completing the hotfix process. The changes from the hotfix are then incorporated into the next regular release to ensure all conflicts resolved during the sync are included in the `release` branch.

### General Guidelines:
- **Reviews:** Since PRs are initiated by the *dotbase-bot*, you are encouraged (and expected) to provide one of the necessary approving reviews yourself.
- **Non-Manual Merges:** It's crucial to note that all merges into the `release` branch are automated and should never be performed manually.

**Comment by Zbozi** [comment]
Good read. To clarify even further I would suggest to seperate the regular release and the the hotfix release even more into distinct paragraphs. 

## Release Process Overview

We categorize our releases into two types: regular releases and hotfix releases. Each type of release boils down to merge into the `release branch but follows a specific process due to the nature of the changes they incorporate.

### General Guidelines:
- **Reviews:** Since PRs are initiated by the *dotbase-bot*, you are encouraged (and expected) to provide one of the necessary approving reviews yourself.
- **Non-Manual Merges:** It's crucial to note that all merges into the `release` branch are automated and should never be performed manually.

### Regular Releases:
- **Merge Process:** Regular releases primarily involve merging changes from the `main` branch into the `release` branch.
- **Automation:** To initiate a regular release, use the *Create Release PR* action on GitHub. This action can be triggered manually either through the GitHub Web UI or via the GitHub CLI.
- **Review and Merge:** The Pull Request (PR) created by the *dotbase-bot* must receive at least two approving reviews. The PR is then merged automatically without manual intervention and is not squashed.
- **Post-Merge Actions:** Following the merge, the `main` branch is fast-forwarded to match the `release` branch. A new GitHub Release and Docker image are then automatically created.

### Hotfix Releases:
- **Need for Hotfixes:** Hotfixes are necessary when urgent changes must be made to a service release, particularly when other changes have already been merged into the `main` branch since the last release.
- **Branch and Merge Process:** Hotfixes are created from a fix branch that includes individual fix commits formatted as `fix: serious bug`. The hotfix branch is then merged into the `release` branch.
- **Automation:** Initiate a hotfix release using the ***Create Hotfix PR*** action on GitHub.
- **Sync with Main:** After the hotfix merge, a sync PR is automatically created from `main` into a branch named `sync/HOTFIX_RELEASE_VERSION_TAG`. Resolving any conflicts between the hotfix and concurrent changes on `main` is necessary before the sync PR can be reviewed and merged.
- **Review and Merge:** The sync PR requires at least one approving review and, like other merges, it is performed automatically and should not be done manually.
- **Post-Merge Actions:** Once merged, `main` is fast-forwarded to the sync branch, completing the hotfix process. The changes from the hotfix are then incorporated into the next regular release to ensure all conflicts resolved during the sync are included in the `release` branch.

**Comment by velramiir** [comment]
Thanks, I incorporated your feedback :)
